"""Shared Polymarket-question → Odds-API sport_key mapping.

Polymarket sports questions don't carry league metadata explicitly. The
team names ARE the only signal — "FC Barcelona vs. Real Madrid: O/U 2.5"
tells us this is La Liga (or maybe Champions League, but we pick the
likeliest league and let the downstream event matcher confirm).

Used by:
  - services.odds_divergence_signal (Strategy B)
  - services.event_fetcher.TheOddsApiAdapter (context provider)

Ordering matters — `_resolve_sport_key` checks substrings in order, so
longer / more-distinctive keywords MUST come before shorter ones. Example:
  "Athletics" (MLB Oakland) must come before "Athletic" (Athletic Bilbao
  La Liga), otherwise Athletics gets mis-routed to La Liga.

Keep this file maintained as we observe new market patterns in production.
A wrong sport_key produces a no_match downstream (event matching fails) —
not a crash — but wastes an API credit. Missing a keyword means we never
even try.
"""
from __future__ import annotations

from typing import Tuple


# (keyword, sport_key). Keyword match is case-insensitive substring on the
# Polymarket question + market_json. Listed in priority order: longest /
# most-specific first to avoid the "Athletics → Athletic" collision class.
SPORT_KEYWORDS: Tuple[Tuple[str, str], ...] = (
    # ─── American sports leagues (have explicit league acronyms in some markets) ───
    ("UEFA Champions League", "soccer_uefa_champs_league"),
    ("UEFA Europa League", "soccer_uefa_europa_league"),
    ("Champions League", "soccer_uefa_champs_league"),
    ("EFL Championship", "soccer_efl_champ"),
    ("Premier League", "soccer_epl"),
    ("Bundesliga 2", "soccer_germany_bundesliga2"),
    ("2. Bundesliga", "soccer_germany_bundesliga2"),
    ("Bundesliga", "soccer_germany_bundesliga"),
    ("Serie A", "soccer_italy_serie_a"),
    ("Ligue 1", "soccer_france_ligue_one"),
    ("Ligue 2", "soccer_france_ligue_two"),
    ("La Liga", "soccer_spain_la_liga"),
    ("Liga MX", "soccer_mexico_ligamx"),
    ("Eredivisie", "soccer_netherlands_eredivisie"),
    ("Primeira Liga", "soccer_portugal_primeira_liga"),
    ("Saudi Pro League", "soccer_saudi_arabia_pro_league"),
    ("Chinese Super League", "soccer_china_superleague"),
    ("J-League", "soccer_japan_j_league"),

    # ─── NBA — all 30 teams (no clear keyword in many questions) ───
    ("Trail Blazers", "basketball_nba"),
    ("Timberwolves", "basketball_nba"),
    ("76ers", "basketball_nba"),
    ("Mavericks", "basketball_nba"),
    ("Grizzlies", "basketball_nba"),
    ("Pelicans", "basketball_nba"),
    ("Cavaliers", "basketball_nba"),
    ("Thunder", "basketball_nba"),
    ("Clippers", "basketball_nba"),
    ("Warriors", "basketball_nba"),
    ("Raptors", "basketball_nba"),
    ("Rockets", "basketball_nba"),
    ("Nuggets", "basketball_nba"),
    ("Hornets", "basketball_nba"),
    ("Celtics", "basketball_nba"),
    ("Wizards", "basketball_nba"),
    ("Pistons", "basketball_nba"),
    ("Knicks", "basketball_nba"),
    ("Lakers", "basketball_nba"),
    ("Bucks", "basketball_nba"),
    ("Bulls", "basketball_nba"),
    ("Magic", "basketball_nba"),
    ("Heat", "basketball_nba"),
    ("Jazz", "basketball_nba"),
    ("Kings", "basketball_nba"),
    ("Hawks", "basketball_nba"),
    ("Spurs", "basketball_nba"),
    ("Suns", "basketball_nba"),
    ("Nets", "basketball_nba"),
    # NBA also has explicit "NBA" keyword as fallback
    ("NBA", "basketball_nba"),

    # ─── WNBA ───
    ("Atlanta Dream", "basketball_wnba"),
    ("Dallas Wings", "basketball_wnba"),
    ("Minnesota Lynx", "basketball_wnba"),
    ("Connecticut Sun", "basketball_wnba"),
    ("New York Liberty", "basketball_wnba"),
    ("Las Vegas Aces", "basketball_wnba"),
    ("Chicago Sky", "basketball_wnba"),
    ("Phoenix Mercury", "basketball_wnba"),
    ("Seattle Storm", "basketball_wnba"),
    ("Washington Mystics", "basketball_wnba"),
    ("Indiana Fever", "basketball_wnba"),
    ("Los Angeles Sparks", "basketball_wnba"),
    ("WNBA", "basketball_wnba"),

    # ─── MLB — 30 teams ("Athletics" BEFORE "Athletic" to avoid La Liga collision) ───
    ("Athletics", "baseball_mlb"),
    ("Diamondbacks", "baseball_mlb"),
    ("Blue Jays", "baseball_mlb"),
    ("White Sox", "baseball_mlb"),
    ("Red Sox", "baseball_mlb"),
    ("Yankees", "baseball_mlb"),
    ("Dodgers", "baseball_mlb"),
    ("Mariners", "baseball_mlb"),
    ("Brewers", "baseball_mlb"),
    ("Phillies", "baseball_mlb"),
    ("Nationals", "baseball_mlb"),
    ("Guardians", "baseball_mlb"),
    ("Pirates", "baseball_mlb"),
    ("Royals", "baseball_mlb"),
    ("Rockies", "baseball_mlb"),
    ("Astros", "baseball_mlb"),
    ("Orioles", "baseball_mlb"),
    ("Marlins", "baseball_mlb"),
    ("Padres", "baseball_mlb"),
    ("Tigers", "baseball_mlb"),
    ("Twins", "baseball_mlb"),
    ("Braves", "baseball_mlb"),
    ("Angels", "baseball_mlb"),
    ("Reds", "baseball_mlb"),
    ("Cubs", "baseball_mlb"),
    ("Mets", "baseball_mlb"),
    ("Rays", "baseball_mlb"),
    # Ambiguous: Cardinals(MLB)/Cardinals(NFL), Giants(MLB)/Giants(NFL),
    # Rangers(MLB)/Rangers(NHL). Resolved by ordering below; MLB-specific
    # variants come first for the most common Polymarket usage.
    ("Cardinals", "baseball_mlb"),
    ("Giants", "baseball_mlb"),
    ("Rangers", "baseball_mlb"),
    ("MLB", "baseball_mlb"),

    # ─── NFL — 32 teams (rarely have ambiguous names with NBA/MLB) ───
    ("49ers", "americanfootball_nfl"),
    ("Buccaneers", "americanfootball_nfl"),
    ("Commanders", "americanfootball_nfl"),
    ("Seahawks", "americanfootball_nfl"),
    ("Cowboys", "americanfootball_nfl"),
    ("Patriots", "americanfootball_nfl"),
    ("Steelers", "americanfootball_nfl"),
    ("Bengals", "americanfootball_nfl"),
    ("Broncos", "americanfootball_nfl"),
    ("Chargers", "americanfootball_nfl"),
    ("Dolphins", "americanfootball_nfl"),
    ("Jaguars", "americanfootball_nfl"),
    ("Panthers", "americanfootball_nfl"),
    ("Falcons", "americanfootball_nfl"),
    ("Vikings", "americanfootball_nfl"),
    ("Packers", "americanfootball_nfl"),
    ("Eagles", "americanfootball_nfl"),
    ("Raiders", "americanfootball_nfl"),
    ("Ravens", "americanfootball_nfl"),
    ("Saints", "americanfootball_nfl"),
    ("Texans", "americanfootball_nfl"),
    ("Browns", "americanfootball_nfl"),
    ("Titans", "americanfootball_nfl"),
    ("Chiefs", "americanfootball_nfl"),
    ("Lions", "americanfootball_nfl"),
    ("Bears", "americanfootball_nfl"),
    ("Bills", "americanfootball_nfl"),
    ("Jets", "americanfootball_nfl"),
    ("Rams", "americanfootball_nfl"),
    ("Colts", "americanfootball_nfl"),
    ("NFL", "americanfootball_nfl"),

    # ─── NHL — major teams ───
    ("Oilers", "icehockey_nhl"),
    ("Maple Leafs", "icehockey_nhl"),
    ("Canadiens", "icehockey_nhl"),
    ("Bruins", "icehockey_nhl"),
    ("Penguins", "icehockey_nhl"),
    ("Blackhawks", "icehockey_nhl"),
    ("Capitals", "icehockey_nhl"),
    ("Avalanche", "icehockey_nhl"),
    ("Lightning", "icehockey_nhl"),
    ("Senators", "icehockey_nhl"),
    ("NHL", "icehockey_nhl"),

    # ─── La Liga (Spanish 1st div) — distinctive team names ───
    ("FC Barcelona", "soccer_spain_la_liga"),
    ("Real Madrid", "soccer_spain_la_liga"),
    ("Real Betis Balompié", "soccer_spain_la_liga"),
    ("Real Betis", "soccer_spain_la_liga"),
    ("Real Sociedad", "soccer_spain_la_liga"),
    ("Atlético de Madrid", "soccer_spain_la_liga"),
    ("Athletic Club", "soccer_spain_la_liga"),
    ("Athletic Bilbao", "soccer_spain_la_liga"),
    ("Sevilla", "soccer_spain_la_liga"),
    ("Valencia CF", "soccer_spain_la_liga"),
    ("Villarreal", "soccer_spain_la_liga"),
    ("Mallorca", "soccer_spain_la_liga"),
    ("Alavés", "soccer_spain_la_liga"),
    ("Alaves", "soccer_spain_la_liga"),
    ("Getafe", "soccer_spain_la_liga"),
    ("Osasuna", "soccer_spain_la_liga"),
    ("Celta", "soccer_spain_la_liga"),
    ("Espanyol", "soccer_spain_la_liga"),
    ("Las Palmas", "soccer_spain_la_liga"),
    ("Levante", "soccer_spain_la_liga"),
    ("Rayo Vallecano", "soccer_spain_la_liga"),
    ("Girona", "soccer_spain_la_liga"),
    ("Elche", "soccer_spain_la_liga"),

    # ─── Spanish 2nd div (Segunda) ───
    ("Albacete", "soccer_spain_segunda_division"),
    ("Cultural Leonesa", "soccer_spain_segunda_division"),
    ("SD Eibar", "soccer_spain_segunda_division"),

    # ─── Premier League — distinctive teams ───
    ("Manchester City", "soccer_epl"),
    ("Manchester United", "soccer_epl"),
    ("Arsenal FC", "soccer_epl"),
    ("Liverpool FC", "soccer_epl"),
    ("Chelsea FC", "soccer_epl"),
    ("Tottenham Hotspur", "soccer_epl"),
    ("Tottenham", "soccer_epl"),
    ("Newcastle United", "soccer_epl"),
    ("West Ham", "soccer_epl"),
    ("Aston Villa", "soccer_epl"),
    ("Fulham FC", "soccer_epl"),
    ("Crystal Palace", "soccer_epl"),
    ("Brighton", "soccer_epl"),
    ("Brentford", "soccer_epl"),
    ("Wolverhampton", "soccer_epl"),
    ("Nottingham Forest", "soccer_epl"),

    # ─── EFL Championship (English 2nd tier) ───
    ("Middlesbrough", "soccer_efl_champ"),
    ("Southampton FC", "soccer_efl_champ"),
    ("Hull City", "soccer_efl_champ"),
    ("Millwall", "soccer_efl_champ"),
    ("Sheffield United", "soccer_efl_champ"),
    ("Leeds United", "soccer_efl_champ"),
    ("Birmingham City", "soccer_efl_champ"),
    ("Sunderland", "soccer_efl_champ"),
    ("Norwich City", "soccer_efl_champ"),

    # ─── Bundesliga (German 1st div) ───
    ("Bayern München", "soccer_germany_bundesliga"),
    ("Bayern Munich", "soccer_germany_bundesliga"),
    ("Borussia Dortmund", "soccer_germany_bundesliga"),
    ("Bayer 04 Leverkusen", "soccer_germany_bundesliga"),
    ("Bayer Leverkusen", "soccer_germany_bundesliga"),
    ("RB Leipzig", "soccer_germany_bundesliga"),
    ("Eintracht Frankfurt", "soccer_germany_bundesliga"),
    ("FC Heidenheim", "soccer_germany_bundesliga"),
    ("Mainz 05", "soccer_germany_bundesliga"),
    ("Union Berlin", "soccer_germany_bundesliga"),
    ("FC Augsburg", "soccer_germany_bundesliga"),
    ("VfB Stuttgart", "soccer_germany_bundesliga"),
    ("Werder Bremen", "soccer_germany_bundesliga"),
    ("VfL Wolfsburg", "soccer_germany_bundesliga"),
    ("Bochum", "soccer_germany_bundesliga"),
    ("Hoffenheim", "soccer_germany_bundesliga"),
    ("Köln", "soccer_germany_bundesliga"),
    ("Mönchengladbach", "soccer_germany_bundesliga"),
    ("Freiburg", "soccer_germany_bundesliga"),

    # ─── 2. Bundesliga ───
    ("Kaiserslautern", "soccer_germany_bundesliga2"),
    ("Hertha BSC", "soccer_germany_bundesliga2"),
    ("FC Magdeburg", "soccer_germany_bundesliga2"),
    ("Magdeburg", "soccer_germany_bundesliga2"),
    ("Nürnberg", "soccer_germany_bundesliga2"),
    ("FC Schalke 04", "soccer_germany_bundesliga2"),
    ("Schalke 04", "soccer_germany_bundesliga2"),
    ("DSC Arminia Bielefeld", "soccer_germany_bundesliga2"),
    ("Arminia Bielefeld", "soccer_germany_bundesliga2"),
    ("Eintracht Braunschweig", "soccer_germany_bundesliga2"),
    ("St. Pauli", "soccer_germany_bundesliga2"),
    ("Hamburger SV", "soccer_germany_bundesliga2"),

    # ─── Serie A (Italian 1st div) ───
    ("Internazionale", "soccer_italy_serie_a"),
    ("Inter Milan", "soccer_italy_serie_a"),
    ("AC Milan", "soccer_italy_serie_a"),
    ("Juventus", "soccer_italy_serie_a"),
    ("Napoli", "soccer_italy_serie_a"),
    ("AS Roma", "soccer_italy_serie_a"),
    ("Lazio", "soccer_italy_serie_a"),
    ("SS Lazio", "soccer_italy_serie_a"),
    ("Atalanta", "soccer_italy_serie_a"),
    ("Fiorentina", "soccer_italy_serie_a"),
    ("Bologna", "soccer_italy_serie_a"),
    ("Torino", "soccer_italy_serie_a"),
    ("Genoa CFC", "soccer_italy_serie_a"),
    ("Empoli", "soccer_italy_serie_a"),
    ("Udinese", "soccer_italy_serie_a"),
    ("Sassuolo", "soccer_italy_serie_a"),

    # ─── Ligue 1 (French 1st div) ───
    ("Paris Saint-Germain", "soccer_france_ligue_one"),
    ("Paris SG", "soccer_france_ligue_one"),
    ("Olympique de Marseille", "soccer_france_ligue_one"),
    ("Olympique Lyonnais", "soccer_france_ligue_one"),
    ("AS Monaco", "soccer_france_ligue_one"),
    ("LOSC Lille", "soccer_france_ligue_one"),
    ("OGC Nice", "soccer_france_ligue_one"),
    ("RC Strasbourg", "soccer_france_ligue_one"),
    ("Stade Rennais", "soccer_france_ligue_one"),
    ("Racing Club de Lens", "soccer_france_ligue_one"),
    ("Angers SCO", "soccer_france_ligue_one"),
    ("Montpellier", "soccer_france_ligue_one"),

    # ─── Ligue 2 ───
    ("Amiens SC", "soccer_france_ligue_two"),
    ("Red Star FC", "soccer_france_ligue_two"),

    # ─── MLS ───
    ("Atlanta United", "soccer_usa_mls"),
    ("CF Montréal", "soccer_usa_mls"),
    ("LA Galaxy", "soccer_usa_mls"),
    ("LAFC", "soccer_usa_mls"),
    ("Inter Miami", "soccer_usa_mls"),
    ("Seattle Sounders", "soccer_usa_mls"),
    ("Portland Timbers", "soccer_usa_mls"),
    ("New York City FC", "soccer_usa_mls"),
    ("New York Red Bulls", "soccer_usa_mls"),
    ("MLS", "soccer_usa_mls"),

    # ─── Eredivisie (Dutch 1st div) ───
    ("Ajax", "soccer_netherlands_eredivisie"),
    ("PSV Eindhoven", "soccer_netherlands_eredivisie"),
    ("Feyenoord", "soccer_netherlands_eredivisie"),
    ("AZ Alkmaar", "soccer_netherlands_eredivisie"),
    ("Twente", "soccer_netherlands_eredivisie"),
    ("Utrecht", "soccer_netherlands_eredivisie"),
    ("Heerenveen", "soccer_netherlands_eredivisie"),

    # ─── Primeira Liga (Portuguese 1st div) ───
    ("Benfica", "soccer_portugal_primeira_liga"),
    ("Sporting CP", "soccer_portugal_primeira_liga"),
    ("FC Porto", "soccer_portugal_primeira_liga"),
    ("SC Braga", "soccer_portugal_primeira_liga"),
    ("Vitória SC", "soccer_portugal_primeira_liga"),
    ("Estrela da Amadora", "soccer_portugal_primeira_liga"),
    ("Famalicão", "soccer_portugal_primeira_liga"),
    ("Santa Clara", "soccer_portugal_primeira_liga"),
    ("CD Nacional", "soccer_portugal_primeira_liga"),
    ("Rio Ave", "soccer_portugal_primeira_liga"),
    ("Gil Vicente", "soccer_portugal_primeira_liga"),
    ("FC Arouca", "soccer_portugal_primeira_liga"),
    ("CD Tondela", "soccer_portugal_primeira_liga"),
    ("Moreirense", "soccer_portugal_primeira_liga"),
    ("Casa Pia", "soccer_portugal_primeira_liga"),

    # ─── Czech First League ───
    ("Slovan Liberec", "soccer_czech_first_league"),
    ("Hradec Králové", "soccer_czech_first_league"),
    ("FC Slovácko", "soccer_czech_first_league"),
    ("Baník Ostrava", "soccer_czech_first_league"),
    ("Mladá Boleslav", "soccer_czech_first_league"),
    ("Sparta Praha", "soccer_czech_first_league"),
    ("Slavia Praha", "soccer_czech_first_league"),

    # ─── Turkish Super Lig ───
    ("Galatasaray", "soccer_turkey_super_league"),
    ("Fenerbahçe", "soccer_turkey_super_league"),
    ("Beşiktaş", "soccer_turkey_super_league"),
    ("Alanyaspor", "soccer_turkey_super_league"),
    ("Kayserispor", "soccer_turkey_super_league"),
    ("Samsunspor", "soccer_turkey_super_league"),
    ("Antalyaspor", "soccer_turkey_super_league"),

    # ─── Argentine Primera División ───
    ("Boca Juniors", "soccer_argentina_primera_division"),
    ("River Plate", "soccer_argentina_primera_division"),
    ("Argentinos Juniors", "soccer_argentina_primera_division"),
    ("CA Huracán", "soccer_argentina_primera_division"),
    ("CA Lanús", "soccer_argentina_primera_division"),
    ("AA Estudiantes", "soccer_argentina_primera_division"),
    ("CA Rosario Central", "soccer_argentina_primera_division"),
    ("San Lorenzo", "soccer_argentina_primera_division"),
    ("Vélez Sarsfield", "soccer_argentina_primera_division"),

    # ─── Brazilian Campeonato (Serie A Brasil) ───
    ("Flamengo", "soccer_brazil_campeonato"),
    ("Palmeiras", "soccer_brazil_campeonato"),
    ("Corinthians", "soccer_brazil_campeonato"),
    ("São Paulo", "soccer_brazil_campeonato"),
    ("Chapecoense", "soccer_brazil_campeonato"),
    ("Red Bull Bragantino", "soccer_brazil_campeonato"),
    ("Cuiabá", "soccer_brazil_campeonato"),
    ("Grêmio", "soccer_brazil_campeonato"),
    ("Internacional", "soccer_brazil_campeonato"),
    ("Cruzeiro", "soccer_brazil_campeonato"),
    ("Atlético Mineiro", "soccer_brazil_campeonato"),
    ("Botafogo", "soccer_brazil_campeonato"),

    # ─── Saudi Pro League ───
    ("Al Nassr", "soccer_saudi_arabia_pro_league"),
    ("Al Hilal", "soccer_saudi_arabia_pro_league"),
    ("Al Ittihad", "soccer_saudi_arabia_pro_league"),
    ("Al Ahli", "soccer_saudi_arabia_pro_league"),
    ("Al Shabab Saudi", "soccer_saudi_arabia_pro_league"),
    ("Al Taawoun", "soccer_saudi_arabia_pro_league"),
    ("Al Riyadh", "soccer_saudi_arabia_pro_league"),
    ("Al Qadisiyah", "soccer_saudi_arabia_pro_league"),
    ("Al Okhdood", "soccer_saudi_arabia_pro_league"),
    ("Al Ettifaq", "soccer_saudi_arabia_pro_league"),
    ("Al Hazem", "soccer_saudi_arabia_pro_league"),
    ("Al Fateh", "soccer_saudi_arabia_pro_league"),

    # ─── J-League ───
    ("Albirex Niigata", "soccer_japan_j_league"),
    ("Nara Club", "soccer_japan_j_league"),
    ("Tokushima Vortis", "soccer_japan_j_league"),
    ("Kyōto Sanga", "soccer_japan_j_league"),
    ("Kyoto Sanga", "soccer_japan_j_league"),
    ("Urawa Reds", "soccer_japan_j_league"),
    ("Kashima Antlers", "soccer_japan_j_league"),
    ("FC Tokyo", "soccer_japan_j_league"),
    ("Yokohama", "soccer_japan_j_league"),

    # ─── Chinese Super League ───
    ("Beijing Guoan", "soccer_china_superleague"),
    ("Shanghai Haigang", "soccer_china_superleague"),
    ("Shanghai SIPG", "soccer_china_superleague"),
    ("Dalian Yingbo", "soccer_china_superleague"),
    ("Qingdao Hainiu", "soccer_china_superleague"),
    ("Qingdao Xihaian", "soccer_china_superleague"),
    ("Henan FC", "soccer_china_superleague"),
    ("Shenzhen Xinpengcheng", "soccer_china_superleague"),
    ("Tianjin Jinmen Hu", "soccer_china_superleague"),
    ("Chengdu Rongcheng", "soccer_china_superleague"),
    ("Zhejiang Zhiye", "soccer_china_superleague"),

    # ─── Colombian Primera ───
    ("Independiente Santa Fe", "soccer_colombia_primera_a"),
    ("América de Cali", "soccer_colombia_primera_a"),
    ("Atlético Nacional", "soccer_colombia_primera_a"),
    ("Millonarios", "soccer_colombia_primera_a"),
)
